// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vsoc_top__Syms.h"


VL_ATTR_COLD void Vsoc_top___024root__trace_init_sub__TOP__0(Vsoc_top___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsoc_top___024root__trace_init_sub__TOP__0\n"); );
    Vsoc_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    const int c = vlSymsp->__Vm_baseCode;
    tracep->pushPrefix("$rootio", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+256,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+257,0,"rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+258,0,"gpio_pin_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+259,0,"gpio_pin_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+260,0,"gpio_pin_dir",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->popPrefix();
    tracep->pushPrefix("soc_top", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+256,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+257,0,"rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+258,0,"gpio_pin_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+259,0,"gpio_pin_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+260,0,"gpio_pin_dir",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+9,0,"cpu_mem_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+10,0,"cpu_mem_instr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+11,0,"cpu_mem_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+12,0,"cpu_mem_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+13,0,"cpu_mem_wdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+14,0,"cpu_mem_wstrb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+2,0,"cpu_mem_rdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+15,0,"cpu_trap",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"rom_ce",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+17,0,"rom_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+18,0,"rom_rdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+19,0,"rom_rdata_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+20,0,"ram_ce",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+21,0,"ram_we",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+22,0,"ram_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->declBus(c+23,0,"ram_rdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+24,0,"ram_rdata_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+25,0,"gpio_mem_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+26,0,"gpio_mem_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+27,0,"gpio_mem_wdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+28,0,"gpio_mem_wstrb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+261,0,"gpio_mem_rdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+29,0,"gpio_mem_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("cpu", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+262,0,"ENABLE_COUNTERS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+262,0,"ENABLE_COUNTERS64",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+262,0,"ENABLE_REGS_16_31",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+262,0,"ENABLE_REGS_DUALPORT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+263,0,"LATCHED_MEM_RDATA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+262,0,"TWO_STAGE_SHIFT",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+263,0,"BARREL_SHIFTER",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+263,0,"TWO_CYCLE_COMPARE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+263,0,"TWO_CYCLE_ALU",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+263,0,"COMPRESSED_ISA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+262,0,"CATCH_MISALIGN",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+262,0,"CATCH_ILLINSN",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+263,0,"ENABLE_PCPI",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+263,0,"ENABLE_MUL",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+263,0,"ENABLE_FAST_MUL",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+263,0,"ENABLE_DIV",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+263,0,"ENABLE_IRQ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+262,0,"ENABLE_IRQ_QREGS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+262,0,"ENABLE_IRQ_TIMER",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+263,0,"ENABLE_TRACE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+263,0,"REGS_INIT_ZERO",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declBus(c+264,0,"MASKED_IRQ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+265,0,"LATCHED_IRQ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+264,0,"PROGADDR_RESET",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+266,0,"PROGADDR_IRQ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+265,0,"STACKADDR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+256,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+257,0,"resetn",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+15,0,"trap",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+9,0,"mem_valid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+10,0,"mem_instr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+11,0,"mem_ready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+12,0,"mem_addr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+13,0,"mem_wdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+14,0,"mem_wstrb",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+2,0,"mem_rdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+3,0,"mem_la_read",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+4,0,"mem_la_write",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+30,0,"mem_la_addr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+31,0,"mem_la_wdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+32,0,"mem_la_wstrb",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+33,0,"pcpi_valid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+34,0,"pcpi_insn",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+35,0,"pcpi_rs1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+36,0,"pcpi_rs2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+267,0,"pcpi_wr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+264,0,"pcpi_rd",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+267,0,"pcpi_wait",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+267,0,"pcpi_ready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+264,0,"irq",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+37,0,"eoi",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+38,0,"trace_valid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declQuad(c+39,0,"trace_data",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 35,0);
    tracep->declBus(c+268,0,"irq_timer",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+269,0,"irq_ebreak",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+270,0,"irq_buserror",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+271,0,"irqregs_offset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+271,0,"regfile_size",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+272,0,"regindex_bits",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBus(c+263,0,"WITH_PCPI",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 0,0);
    tracep->declQuad(c+273,0,"TRACE_BRANCH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 35,0);
    tracep->declQuad(c+275,0,"TRACE_ADDR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 35,0);
    tracep->declQuad(c+277,0,"TRACE_IRQ",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 35,0);
    tracep->declQuad(c+41,0,"count_cycle",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declQuad(c+43,0,"count_instr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declBus(c+45,0,"reg_pc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+46,0,"reg_next_pc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+35,0,"reg_op1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+36,0,"reg_op2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+47,0,"reg_out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+48,0,"reg_sh",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+49,0,"next_insn_opcode",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+50,0,"dbg_insn_opcode",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+51,0,"dbg_insn_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+9,0,"dbg_mem_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+10,0,"dbg_mem_instr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+11,0,"dbg_mem_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+12,0,"dbg_mem_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+13,0,"dbg_mem_wdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+14,0,"dbg_mem_wstrb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+2,0,"dbg_mem_rdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+52,0,"next_pc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+53,0,"irq_delay",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+54,0,"irq_active",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+55,0,"irq_mask",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+56,0,"irq_pending",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+57,0,"timer",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("cpuregs", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+58+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->declBus(c+279,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->declBit(c+267,0,"pcpi_mul_wr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+264,0,"pcpi_mul_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+267,0,"pcpi_mul_wait",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+267,0,"pcpi_mul_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+267,0,"pcpi_div_wr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+264,0,"pcpi_div_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+267,0,"pcpi_div_wait",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+267,0,"pcpi_div_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+267,0,"pcpi_int_wr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+264,0,"pcpi_int_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+267,0,"pcpi_int_wait",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+267,0,"pcpi_int_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+90,0,"mem_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+91,0,"mem_wordsize",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+5,0,"mem_rdata_word",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+92,0,"mem_rdata_q",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+93,0,"mem_do_prefetch",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+94,0,"mem_do_rinst",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+95,0,"mem_do_rdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+96,0,"mem_do_wdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+97,0,"mem_xfer",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+98,0,"mem_la_secondword",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+99,0,"mem_la_firstword_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+100,0,"last_mem_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+267,0,"mem_la_firstword",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+267,0,"mem_la_firstword_xfer",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+101,0,"prefetched_high_word",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+6,0,"clear_prefetched_high_word",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+280,0,"mem_16bit_buffer",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+7,0,"mem_rdata_latched_noshuffle",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+7,0,"mem_rdata_latched",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+267,0,"mem_la_use_prefetched_high_word",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+102,0,"mem_busy",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+8,0,"mem_done",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+103,0,"instr_lui",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+104,0,"instr_auipc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+105,0,"instr_jal",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+106,0,"instr_jalr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+107,0,"instr_beq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+108,0,"instr_bne",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+109,0,"instr_blt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+110,0,"instr_bge",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+111,0,"instr_bltu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+112,0,"instr_bgeu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+113,0,"instr_lb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+114,0,"instr_lh",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+115,0,"instr_lw",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+116,0,"instr_lbu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+117,0,"instr_lhu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+118,0,"instr_sb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+119,0,"instr_sh",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+120,0,"instr_sw",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+121,0,"instr_addi",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+122,0,"instr_slti",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+123,0,"instr_sltiu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+124,0,"instr_xori",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+125,0,"instr_ori",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+126,0,"instr_andi",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+127,0,"instr_slli",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+128,0,"instr_srli",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+129,0,"instr_srai",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+130,0,"instr_add",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+131,0,"instr_sub",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+132,0,"instr_sll",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+133,0,"instr_slt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+134,0,"instr_sltu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+135,0,"instr_xor",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+136,0,"instr_srl",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+137,0,"instr_sra",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+138,0,"instr_or",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+139,0,"instr_and",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+140,0,"instr_rdcycle",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+141,0,"instr_rdcycleh",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+142,0,"instr_rdinstr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+143,0,"instr_rdinstrh",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+144,0,"instr_ecall_ebreak",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+145,0,"instr_fence",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+146,0,"instr_getq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+147,0,"instr_setq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+148,0,"instr_retirq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+149,0,"instr_maskirq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+150,0,"instr_waitirq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+151,0,"instr_timer",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+152,0,"instr_trap",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+153,0,"decoded_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+154,0,"decoded_rs1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+155,0,"decoded_rs2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+156,0,"decoded_imm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+157,0,"decoded_imm_j",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+158,0,"decoder_trigger",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+159,0,"decoder_trigger_q",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+160,0,"decoder_pseudo_trigger",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+161,0,"decoder_pseudo_trigger_q",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+148,0,"compressed_instr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+162,0,"is_lui_auipc_jal",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+163,0,"is_lb_lh_lw_lbu_lhu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+164,0,"is_slli_srli_srai",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+165,0,"is_jalr_addi_slti_sltiu_xori_ori_andi",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+166,0,"is_sb_sh_sw",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+167,0,"is_sll_srl_sra",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+168,0,"is_lui_auipc_jal_jalr_addi_add_sub",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+169,0,"is_slti_blt_slt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+170,0,"is_sltiu_bltu_sltu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+171,0,"is_beq_bne_blt_bge_bltu_bgeu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+172,0,"is_lbu_lhu_lw",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+173,0,"is_alu_reg_imm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+174,0,"is_alu_reg_reg",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+175,0,"is_compare",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+176,0,"is_rdcycle_rdcycleh_rdinstr_rdinstrh",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declQuad(c+177,0,"new_ascii_instr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declQuad(c+179,0,"dbg_ascii_instr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declBus(c+181,0,"dbg_insn_imm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+182,0,"dbg_insn_rs1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+183,0,"dbg_insn_rs2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+184,0,"dbg_insn_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+185,0,"dbg_rs1val",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+186,0,"dbg_rs2val",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+187,0,"dbg_rs1val_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+188,0,"dbg_rs2val_valid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declQuad(c+189,0,"q_ascii_instr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declBus(c+191,0,"q_insn_imm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+192,0,"q_insn_opcode",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+193,0,"q_insn_rs1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+194,0,"q_insn_rs2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+195,0,"q_insn_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBit(c+196,0,"dbg_next",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+197,0,"launch_next_insn",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+198,0,"dbg_valid_insn",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declQuad(c+199,0,"cached_ascii_instr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 63,0);
    tracep->declBus(c+201,0,"cached_insn_imm",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+202,0,"cached_insn_opcode",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+203,0,"cached_insn_rs1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+204,0,"cached_insn_rs2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+205,0,"cached_insn_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+281,0,"cpu_state_trap",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+282,0,"cpu_state_fetch",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+283,0,"cpu_state_ld_rs1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+284,0,"cpu_state_ld_rs2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+285,0,"cpu_state_exec",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+286,0,"cpu_state_shift",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+287,0,"cpu_state_stmem",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+288,0,"cpu_state_ldmem",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+206,0,"cpu_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+207,0,"irq_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declArray(c+208,0,"dbg_ascii_state",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 127,0);
    tracep->declBit(c+212,0,"set_mem_do_rinst",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+213,0,"set_mem_do_rdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+214,0,"set_mem_do_wdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+215,0,"latched_store",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+216,0,"latched_stalu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+217,0,"latched_branch",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+218,0,"latched_compr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+219,0,"latched_trace",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+220,0,"latched_is_lu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+221,0,"latched_is_lh",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+222,0,"latched_is_lb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+223,0,"latched_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+224,0,"current_pc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+289,0,"pcpi_timeout_counter",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+225,0,"pcpi_timeout",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+226,0,"next_irq_pending",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+227,0,"do_waitirq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+228,0,"alu_out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+229,0,"alu_out_q",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+230,0,"alu_out_0",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+231,0,"alu_out_0_q",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+232,0,"alu_wait",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+233,0,"alu_wait_2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+234,0,"alu_add_sub",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+235,0,"alu_shl",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+236,0,"alu_shr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+237,0,"alu_eq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+238,0,"alu_ltu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+239,0,"alu_lts",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+240,0,"clear_prefetched_high_word_q",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+241,0,"cpuregs_write",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+242,0,"cpuregs_wrdata",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+243,0,"cpuregs_rs1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+244,0,"cpuregs_rs2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+290,0,"decoded_rs",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->popPrefix();
    tracep->pushPrefix("data_ram", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+291,0,"ADDR_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+292,0,"DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+256,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+257,0,"rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+20,0,"ce",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+21,0,"we",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+14,0,"wstrb",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+22,0,"addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->declBus(c+13,0,"wdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+23,0,"rdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+24,0,"rdata_valid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+1,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INTEGER, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("decoder", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+9,0,"cpu_mem_valid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+12,0,"cpu_mem_addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+13,0,"cpu_mem_wdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+14,0,"cpu_mem_wstrb",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+2,0,"cpu_mem_rdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+11,0,"cpu_mem_ready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"rom_ce",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+17,0,"rom_addr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+18,0,"rom_rdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+19,0,"rom_rdata_valid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+20,0,"ram_ce",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+21,0,"ram_we",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+22,0,"ram_addr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->declBus(c+23,0,"ram_rdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+24,0,"ram_rdata_valid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+25,0,"gpio_mem_valid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+26,0,"gpio_mem_addr",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+27,0,"gpio_mem_wdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+28,0,"gpio_mem_wstrb",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+261,0,"gpio_mem_rdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+29,0,"gpio_mem_ready",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+245,0,"rom_sel",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+246,0,"ram_sel",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+247,0,"io_sel",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+248,0,"rom_word_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+249,0,"ram_word_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->popPrefix();
    tracep->pushPrefix("gpio_inst", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+256,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+257,0,"rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+25,0,"mem_valid",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+26,0,"mem_addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+27,0,"mem_wdata",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+28,0,"mem_wstrb",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+261,0,"mem_rdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+29,0,"mem_ready",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+258,0,"gpio_pin_in",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+259,0,"gpio_pin_out",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+260,0,"gpio_pin_dir",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+250,0,"ddrb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+251,0,"portb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+252,0,"sel_pinb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+253,0,"sel_ddrb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+254,0,"sel_portb",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+255,0,"gpio_sel",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("program_rom", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+293,0,"ADDR_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+292,0,"DATA_WIDTH",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declArray(c+294,0,"INIT_FILE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 95,0);
    tracep->declBit(c+256,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+257,0,"rst_n",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+16,0,"ce",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+17,0,"addr",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+18,0,"rdata",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+19,0,"rdata_valid",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vsoc_top___024root__trace_init_top(Vsoc_top___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsoc_top___024root__trace_init_top\n"); );
    Vsoc_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    Vsoc_top___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vsoc_top___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
VL_ATTR_COLD void Vsoc_top___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vsoc_top___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vsoc_top___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vsoc_top___024root__trace_register(Vsoc_top___024root* vlSelf, VerilatedVcd* tracep) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsoc_top___024root__trace_register\n"); );
    Vsoc_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    tracep->addConstCb(&Vsoc_top___024root__trace_const_0, 0, vlSelf);
    tracep->addFullCb(&Vsoc_top___024root__trace_full_0, 0, vlSelf);
    tracep->addChgCb(&Vsoc_top___024root__trace_chg_0, 0, vlSelf);
    tracep->addCleanupCb(&Vsoc_top___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vsoc_top___024root__trace_const_0_sub_0(Vsoc_top___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vsoc_top___024root__trace_const_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsoc_top___024root__trace_const_0\n"); );
    // Body
    Vsoc_top___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vsoc_top___024root*>(voidSelf);
    Vsoc_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    Vsoc_top___024root__trace_const_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vsoc_top___024root__trace_const_0_sub_0(Vsoc_top___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsoc_top___024root__trace_const_0_sub_0\n"); );
    Vsoc_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Locals
    VlWide<3>/*95:0*/ __Vtemp_1;
    // Body
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    bufp->fullBit(oldp+262,(1U));
    bufp->fullBit(oldp+263,(0U));
    bufp->fullIData(oldp+264,(0U),32);
    bufp->fullIData(oldp+265,(0xffffffffU),32);
    bufp->fullIData(oldp+266,(0x00000010U),32);
    bufp->fullBit(oldp+267,(0U));
    bufp->fullIData(oldp+268,(0U),32);
    bufp->fullIData(oldp+269,(1U),32);
    bufp->fullIData(oldp+270,(2U),32);
    bufp->fullIData(oldp+271,(0x00000020U),32);
    bufp->fullIData(oldp+272,(5U),32);
    bufp->fullQData(oldp+273,(0x0000000100000000ULL),36);
    bufp->fullQData(oldp+275,(0x0000000200000000ULL),36);
    bufp->fullQData(oldp+277,(0x0000000800000000ULL),36);
    bufp->fullIData(oldp+279,(vlSelfRef.soc_top__DOT__cpu__DOT__i),32);
    bufp->fullSData(oldp+280,(vlSelfRef.soc_top__DOT__cpu__DOT__mem_16bit_buffer),16);
    bufp->fullCData(oldp+281,(0x80U),8);
    bufp->fullCData(oldp+282,(0x40U),8);
    bufp->fullCData(oldp+283,(0x20U),8);
    bufp->fullCData(oldp+284,(0x10U),8);
    bufp->fullCData(oldp+285,(8U),8);
    bufp->fullCData(oldp+286,(4U),8);
    bufp->fullCData(oldp+287,(2U),8);
    bufp->fullCData(oldp+288,(1U),8);
    bufp->fullCData(oldp+289,(vlSelfRef.soc_top__DOT__cpu__DOT__pcpi_timeout_counter),4);
    bufp->fullCData(oldp+290,(0U),5);
    bufp->fullIData(oldp+291,(0x0000000cU),32);
    bufp->fullIData(oldp+292,(0x00000020U),32);
    bufp->fullIData(oldp+293,(0x00000010U),32);
    __Vtemp_1[0U] = 0x2e6d656dU;
    __Vtemp_1[1U] = 0x77617265U;
    __Vtemp_1[2U] = 0x6669726dU;
    bufp->fullWData(oldp+294,(__Vtemp_1),96);
}

VL_ATTR_COLD void Vsoc_top___024root__trace_full_0_sub_0(Vsoc_top___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vsoc_top___024root__trace_full_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsoc_top___024root__trace_full_0\n"); );
    // Body
    Vsoc_top___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vsoc_top___024root*>(voidSelf);
    Vsoc_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    Vsoc_top___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vsoc_top___024root__trace_full_0_sub_0(Vsoc_top___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vsoc_top___024root__trace_full_0_sub_0\n"); );
    Vsoc_top__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    auto& vlSelfRef = std::ref(*vlSelf).get();
    // Body
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    bufp->fullIData(oldp+1,(vlSelfRef.soc_top__DOT__data_ram__DOT__i),32);
    bufp->fullIData(oldp+2,(vlSelfRef.soc_top__DOT__cpu_mem_rdata),32);
    bufp->fullBit(oldp+3,(vlSelfRef.soc_top__DOT__cpu__DOT__mem_la_read));
    bufp->fullBit(oldp+4,(vlSelfRef.soc_top__DOT__cpu__DOT__mem_la_write));
    bufp->fullIData(oldp+5,(vlSelfRef.soc_top__DOT__cpu__DOT__mem_rdata_word),32);
    bufp->fullBit(oldp+6,(vlSelfRef.soc_top__DOT__cpu__DOT__clear_prefetched_high_word));
    bufp->fullIData(oldp+7,(vlSelfRef.soc_top__DOT__cpu__DOT__mem_rdata_latched_noshuffle),32);
    bufp->fullBit(oldp+8,(vlSelfRef.soc_top__DOT__cpu__DOT__mem_done));
    bufp->fullBit(oldp+9,(vlSelfRef.soc_top__DOT__cpu_mem_valid));
    bufp->fullBit(oldp+10,(vlSelfRef.soc_top__DOT__cpu_mem_instr));
    bufp->fullBit(oldp+11,(vlSelfRef.soc_top__DOT__cpu_mem_ready));
    bufp->fullIData(oldp+12,(vlSelfRef.soc_top__DOT__cpu_mem_addr),32);
    bufp->fullIData(oldp+13,(vlSelfRef.soc_top__DOT__cpu_mem_wdata),32);
    bufp->fullCData(oldp+14,(vlSelfRef.soc_top__DOT__cpu_mem_wstrb),4);
    bufp->fullBit(oldp+15,(vlSelfRef.soc_top__DOT__cpu_trap));
    bufp->fullBit(oldp+16,(vlSelfRef.soc_top__DOT__program_rom__DOT__ce));
    bufp->fullSData(oldp+17,(((IData)(vlSelfRef.soc_top__DOT__program_rom__DOT__ce)
                               ? (0x00003fffU & (vlSelfRef.soc_top__DOT__cpu_mem_addr 
                                                 >> 2U))
                               : 0U)),16);
    bufp->fullIData(oldp+18,(vlSelfRef.soc_top__DOT__rom_rdata),32);
    bufp->fullBit(oldp+19,(vlSelfRef.soc_top__DOT__rom_rdata_valid));
    bufp->fullBit(oldp+20,(vlSelfRef.soc_top__DOT__data_ram__DOT__ce));
    bufp->fullBit(oldp+21,(vlSelfRef.soc_top__DOT__data_ram__DOT__we));
    bufp->fullSData(oldp+22,(vlSelfRef.soc_top__DOT__data_ram__DOT__addr),12);
    bufp->fullIData(oldp+23,(vlSelfRef.soc_top__DOT__ram_rdata),32);
    bufp->fullBit(oldp+24,(vlSelfRef.soc_top__DOT__ram_rdata_valid));
    bufp->fullBit(oldp+25,(vlSelfRef.soc_top__DOT__gpio_inst__DOT__mem_valid));
    bufp->fullIData(oldp+26,(vlSelfRef.soc_top__DOT__gpio_inst__DOT__mem_addr),32);
    bufp->fullIData(oldp+27,(vlSelfRef.soc_top__DOT__gpio_inst__DOT__mem_wdata),32);
    bufp->fullCData(oldp+28,(vlSelfRef.soc_top__DOT__gpio_inst__DOT__mem_wstrb),4);
    bufp->fullBit(oldp+29,(vlSelfRef.soc_top__DOT__gpio_mem_ready));
    bufp->fullIData(oldp+30,((((IData)(vlSelfRef.soc_top__DOT__cpu__DOT__mem_do_prefetch) 
                               | (IData)(vlSelfRef.soc_top__DOT__cpu__DOT__mem_do_rinst))
                               ? (0xfffffffcU & vlSelfRef.soc_top__DOT__cpu__DOT__next_pc)
                               : (0xfffffffcU & vlSelfRef.soc_top__DOT__cpu__DOT__reg_op1))),32);
    bufp->fullIData(oldp+31,(vlSelfRef.soc_top__DOT__cpu__DOT__mem_la_wdata),32);
    bufp->fullCData(oldp+32,(vlSelfRef.soc_top__DOT__cpu__DOT__mem_la_wstrb),4);
    bufp->fullBit(oldp+33,(vlSelfRef.soc_top__DOT__cpu__DOT__pcpi_valid));
    bufp->fullIData(oldp+34,(vlSelfRef.soc_top__DOT__cpu__DOT__pcpi_insn),32);
    bufp->fullIData(oldp+35,(vlSelfRef.soc_top__DOT__cpu__DOT__reg_op1),32);
    bufp->fullIData(oldp+36,(vlSelfRef.soc_top__DOT__cpu__DOT__reg_op2),32);
    bufp->fullIData(oldp+37,(vlSelfRef.soc_top__DOT__cpu__DOT__eoi),32);
    bufp->fullBit(oldp+38,(vlSelfRef.soc_top__DOT__cpu__DOT__trace_valid));
    bufp->fullQData(oldp+39,(vlSelfRef.soc_top__DOT__cpu__DOT__trace_data),36);
    bufp->fullQData(oldp+41,(vlSelfRef.soc_top__DOT__cpu__DOT__count_cycle),64);
    bufp->fullQData(oldp+43,(vlSelfRef.soc_top__DOT__cpu__DOT__count_instr),64);
    bufp->fullIData(oldp+45,(vlSelfRef.soc_top__DOT__cpu__DOT__reg_pc),32);
    bufp->fullIData(oldp+46,(vlSelfRef.soc_top__DOT__cpu__DOT__reg_next_pc),32);
    bufp->fullIData(oldp+47,(vlSelfRef.soc_top__DOT__cpu__DOT__reg_out),32);
    bufp->fullCData(oldp+48,(vlSelfRef.soc_top__DOT__cpu__DOT__reg_sh),5);
    bufp->fullIData(oldp+49,(vlSelfRef.soc_top__DOT__cpu__DOT__next_insn_opcode),32);
    bufp->fullIData(oldp+50,(vlSelfRef.soc_top__DOT__cpu__DOT__dbg_insn_opcode),32);
    bufp->fullIData(oldp+51,(vlSelfRef.soc_top__DOT__cpu__DOT__dbg_insn_addr),32);
    bufp->fullIData(oldp+52,(vlSelfRef.soc_top__DOT__cpu__DOT__next_pc),32);
    bufp->fullBit(oldp+53,(vlSelfRef.soc_top__DOT__cpu__DOT__irq_delay));
    bufp->fullBit(oldp+54,(vlSelfRef.soc_top__DOT__cpu__DOT__irq_active));
    bufp->fullIData(oldp+55,(vlSelfRef.soc_top__DOT__cpu__DOT__irq_mask),32);
    bufp->fullIData(oldp+56,(vlSelfRef.soc_top__DOT__cpu__DOT__irq_pending),32);
    bufp->fullIData(oldp+57,(vlSelfRef.soc_top__DOT__cpu__DOT__timer),32);
    bufp->fullIData(oldp+58,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[0]),32);
    bufp->fullIData(oldp+59,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[1]),32);
    bufp->fullIData(oldp+60,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[2]),32);
    bufp->fullIData(oldp+61,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[3]),32);
    bufp->fullIData(oldp+62,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[4]),32);
    bufp->fullIData(oldp+63,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[5]),32);
    bufp->fullIData(oldp+64,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[6]),32);
    bufp->fullIData(oldp+65,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[7]),32);
    bufp->fullIData(oldp+66,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[8]),32);
    bufp->fullIData(oldp+67,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[9]),32);
    bufp->fullIData(oldp+68,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[10]),32);
    bufp->fullIData(oldp+69,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[11]),32);
    bufp->fullIData(oldp+70,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[12]),32);
    bufp->fullIData(oldp+71,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[13]),32);
    bufp->fullIData(oldp+72,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[14]),32);
    bufp->fullIData(oldp+73,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[15]),32);
    bufp->fullIData(oldp+74,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[16]),32);
    bufp->fullIData(oldp+75,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[17]),32);
    bufp->fullIData(oldp+76,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[18]),32);
    bufp->fullIData(oldp+77,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[19]),32);
    bufp->fullIData(oldp+78,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[20]),32);
    bufp->fullIData(oldp+79,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[21]),32);
    bufp->fullIData(oldp+80,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[22]),32);
    bufp->fullIData(oldp+81,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[23]),32);
    bufp->fullIData(oldp+82,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[24]),32);
    bufp->fullIData(oldp+83,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[25]),32);
    bufp->fullIData(oldp+84,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[26]),32);
    bufp->fullIData(oldp+85,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[27]),32);
    bufp->fullIData(oldp+86,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[28]),32);
    bufp->fullIData(oldp+87,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[29]),32);
    bufp->fullIData(oldp+88,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[30]),32);
    bufp->fullIData(oldp+89,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs[31]),32);
    bufp->fullCData(oldp+90,(vlSelfRef.soc_top__DOT__cpu__DOT__mem_state),2);
    bufp->fullCData(oldp+91,(vlSelfRef.soc_top__DOT__cpu__DOT__mem_wordsize),2);
    bufp->fullIData(oldp+92,(vlSelfRef.soc_top__DOT__cpu__DOT__mem_rdata_q),32);
    bufp->fullBit(oldp+93,(vlSelfRef.soc_top__DOT__cpu__DOT__mem_do_prefetch));
    bufp->fullBit(oldp+94,(vlSelfRef.soc_top__DOT__cpu__DOT__mem_do_rinst));
    bufp->fullBit(oldp+95,(vlSelfRef.soc_top__DOT__cpu__DOT__mem_do_rdata));
    bufp->fullBit(oldp+96,(vlSelfRef.soc_top__DOT__cpu__DOT__mem_do_wdata));
    bufp->fullBit(oldp+97,(vlSelfRef.soc_top__DOT__cpu__DOT__mem_xfer));
    bufp->fullBit(oldp+98,(vlSelfRef.soc_top__DOT__cpu__DOT__mem_la_secondword));
    bufp->fullBit(oldp+99,(vlSelfRef.soc_top__DOT__cpu__DOT__mem_la_firstword_reg));
    bufp->fullBit(oldp+100,(vlSelfRef.soc_top__DOT__cpu__DOT__last_mem_valid));
    bufp->fullBit(oldp+101,(vlSelfRef.soc_top__DOT__cpu__DOT__prefetched_high_word));
    bufp->fullBit(oldp+102,(((IData)(vlSelfRef.soc_top__DOT__cpu__DOT__mem_do_prefetch) 
                             | (IData)(vlSelfRef.soc_top__DOT__cpu__DOT____VdfgRegularize_h233421b0_0_0))));
    bufp->fullBit(oldp+103,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_lui));
    bufp->fullBit(oldp+104,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_auipc));
    bufp->fullBit(oldp+105,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_jal));
    bufp->fullBit(oldp+106,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_jalr));
    bufp->fullBit(oldp+107,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_beq));
    bufp->fullBit(oldp+108,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_bne));
    bufp->fullBit(oldp+109,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_blt));
    bufp->fullBit(oldp+110,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_bge));
    bufp->fullBit(oldp+111,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_bltu));
    bufp->fullBit(oldp+112,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_bgeu));
    bufp->fullBit(oldp+113,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_lb));
    bufp->fullBit(oldp+114,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_lh));
    bufp->fullBit(oldp+115,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_lw));
    bufp->fullBit(oldp+116,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_lbu));
    bufp->fullBit(oldp+117,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_lhu));
    bufp->fullBit(oldp+118,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_sb));
    bufp->fullBit(oldp+119,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_sh));
    bufp->fullBit(oldp+120,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_sw));
    bufp->fullBit(oldp+121,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_addi));
    bufp->fullBit(oldp+122,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_slti));
    bufp->fullBit(oldp+123,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_sltiu));
    bufp->fullBit(oldp+124,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_xori));
    bufp->fullBit(oldp+125,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_ori));
    bufp->fullBit(oldp+126,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_andi));
    bufp->fullBit(oldp+127,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_slli));
    bufp->fullBit(oldp+128,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_srli));
    bufp->fullBit(oldp+129,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_srai));
    bufp->fullBit(oldp+130,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_add));
    bufp->fullBit(oldp+131,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_sub));
    bufp->fullBit(oldp+132,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_sll));
    bufp->fullBit(oldp+133,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_slt));
    bufp->fullBit(oldp+134,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_sltu));
    bufp->fullBit(oldp+135,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_xor));
    bufp->fullBit(oldp+136,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_srl));
    bufp->fullBit(oldp+137,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_sra));
    bufp->fullBit(oldp+138,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_or));
    bufp->fullBit(oldp+139,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_and));
    bufp->fullBit(oldp+140,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_rdcycle));
    bufp->fullBit(oldp+141,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_rdcycleh));
    bufp->fullBit(oldp+142,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_rdinstr));
    bufp->fullBit(oldp+143,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_rdinstrh));
    bufp->fullBit(oldp+144,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_ecall_ebreak));
    bufp->fullBit(oldp+145,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_fence));
    bufp->fullBit(oldp+146,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_getq));
    bufp->fullBit(oldp+147,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_setq));
    bufp->fullBit(oldp+148,(vlSelfRef.soc_top__DOT__cpu__DOT__compressed_instr));
    bufp->fullBit(oldp+149,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_maskirq));
    bufp->fullBit(oldp+150,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_waitirq));
    bufp->fullBit(oldp+151,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_timer));
    bufp->fullBit(oldp+152,(vlSelfRef.soc_top__DOT__cpu__DOT__instr_trap));
    bufp->fullCData(oldp+153,(vlSelfRef.soc_top__DOT__cpu__DOT__decoded_rd),5);
    bufp->fullCData(oldp+154,(vlSelfRef.soc_top__DOT__cpu__DOT__decoded_rs1),5);
    bufp->fullCData(oldp+155,(vlSelfRef.soc_top__DOT__cpu__DOT__decoded_rs2),5);
    bufp->fullIData(oldp+156,(vlSelfRef.soc_top__DOT__cpu__DOT__decoded_imm),32);
    bufp->fullIData(oldp+157,(vlSelfRef.soc_top__DOT__cpu__DOT__decoded_imm_j),32);
    bufp->fullBit(oldp+158,(vlSelfRef.soc_top__DOT__cpu__DOT__decoder_trigger));
    bufp->fullBit(oldp+159,(vlSelfRef.soc_top__DOT__cpu__DOT__decoder_trigger_q));
    bufp->fullBit(oldp+160,(vlSelfRef.soc_top__DOT__cpu__DOT__decoder_pseudo_trigger));
    bufp->fullBit(oldp+161,(vlSelfRef.soc_top__DOT__cpu__DOT__decoder_pseudo_trigger_q));
    bufp->fullBit(oldp+162,(vlSelfRef.soc_top__DOT__cpu__DOT__is_lui_auipc_jal));
    bufp->fullBit(oldp+163,(vlSelfRef.soc_top__DOT__cpu__DOT__is_lb_lh_lw_lbu_lhu));
    bufp->fullBit(oldp+164,(vlSelfRef.soc_top__DOT__cpu__DOT__is_slli_srli_srai));
    bufp->fullBit(oldp+165,(vlSelfRef.soc_top__DOT__cpu__DOT__is_jalr_addi_slti_sltiu_xori_ori_andi));
    bufp->fullBit(oldp+166,(vlSelfRef.soc_top__DOT__cpu__DOT__is_sb_sh_sw));
    bufp->fullBit(oldp+167,(vlSelfRef.soc_top__DOT__cpu__DOT__is_sll_srl_sra));
    bufp->fullBit(oldp+168,(vlSelfRef.soc_top__DOT__cpu__DOT__is_lui_auipc_jal_jalr_addi_add_sub));
    bufp->fullBit(oldp+169,(vlSelfRef.soc_top__DOT__cpu__DOT__is_slti_blt_slt));
    bufp->fullBit(oldp+170,(vlSelfRef.soc_top__DOT__cpu__DOT__is_sltiu_bltu_sltu));
    bufp->fullBit(oldp+171,(vlSelfRef.soc_top__DOT__cpu__DOT__is_beq_bne_blt_bge_bltu_bgeu));
    bufp->fullBit(oldp+172,(vlSelfRef.soc_top__DOT__cpu__DOT__is_lbu_lhu_lw));
    bufp->fullBit(oldp+173,(vlSelfRef.soc_top__DOT__cpu__DOT__is_alu_reg_imm));
    bufp->fullBit(oldp+174,(vlSelfRef.soc_top__DOT__cpu__DOT__is_alu_reg_reg));
    bufp->fullBit(oldp+175,(vlSelfRef.soc_top__DOT__cpu__DOT__is_compare));
    bufp->fullBit(oldp+176,(vlSelfRef.soc_top__DOT__cpu__DOT__is_rdcycle_rdcycleh_rdinstr_rdinstrh));
    bufp->fullQData(oldp+177,(vlSelfRef.soc_top__DOT__cpu__DOT__new_ascii_instr),64);
    bufp->fullQData(oldp+179,(vlSelfRef.soc_top__DOT__cpu__DOT__dbg_ascii_instr),64);
    bufp->fullIData(oldp+181,(vlSelfRef.soc_top__DOT__cpu__DOT__dbg_insn_imm),32);
    bufp->fullCData(oldp+182,(vlSelfRef.soc_top__DOT__cpu__DOT__dbg_insn_rs1),5);
    bufp->fullCData(oldp+183,(vlSelfRef.soc_top__DOT__cpu__DOT__dbg_insn_rs2),5);
    bufp->fullCData(oldp+184,(vlSelfRef.soc_top__DOT__cpu__DOT__dbg_insn_rd),5);
    bufp->fullIData(oldp+185,(vlSelfRef.soc_top__DOT__cpu__DOT__dbg_rs1val),32);
    bufp->fullIData(oldp+186,(vlSelfRef.soc_top__DOT__cpu__DOT__dbg_rs2val),32);
    bufp->fullBit(oldp+187,(vlSelfRef.soc_top__DOT__cpu__DOT__dbg_rs1val_valid));
    bufp->fullBit(oldp+188,(vlSelfRef.soc_top__DOT__cpu__DOT__dbg_rs2val_valid));
    bufp->fullQData(oldp+189,(vlSelfRef.soc_top__DOT__cpu__DOT__q_ascii_instr),64);
    bufp->fullIData(oldp+191,(vlSelfRef.soc_top__DOT__cpu__DOT__q_insn_imm),32);
    bufp->fullIData(oldp+192,(vlSelfRef.soc_top__DOT__cpu__DOT__q_insn_opcode),32);
    bufp->fullCData(oldp+193,(vlSelfRef.soc_top__DOT__cpu__DOT__q_insn_rs1),5);
    bufp->fullCData(oldp+194,(vlSelfRef.soc_top__DOT__cpu__DOT__q_insn_rs2),5);
    bufp->fullCData(oldp+195,(vlSelfRef.soc_top__DOT__cpu__DOT__q_insn_rd),5);
    bufp->fullBit(oldp+196,(vlSelfRef.soc_top__DOT__cpu__DOT__dbg_next));
    bufp->fullBit(oldp+197,(vlSelfRef.soc_top__DOT__cpu__DOT__launch_next_insn));
    bufp->fullBit(oldp+198,(vlSelfRef.soc_top__DOT__cpu__DOT__dbg_valid_insn));
    bufp->fullQData(oldp+199,(vlSelfRef.soc_top__DOT__cpu__DOT__cached_ascii_instr),64);
    bufp->fullIData(oldp+201,(vlSelfRef.soc_top__DOT__cpu__DOT__cached_insn_imm),32);
    bufp->fullIData(oldp+202,(vlSelfRef.soc_top__DOT__cpu__DOT__cached_insn_opcode),32);
    bufp->fullCData(oldp+203,(vlSelfRef.soc_top__DOT__cpu__DOT__cached_insn_rs1),5);
    bufp->fullCData(oldp+204,(vlSelfRef.soc_top__DOT__cpu__DOT__cached_insn_rs2),5);
    bufp->fullCData(oldp+205,(vlSelfRef.soc_top__DOT__cpu__DOT__cached_insn_rd),5);
    bufp->fullCData(oldp+206,(vlSelfRef.soc_top__DOT__cpu__DOT__cpu_state),8);
    bufp->fullCData(oldp+207,(vlSelfRef.soc_top__DOT__cpu__DOT__irq_state),2);
    bufp->fullWData(oldp+208,(vlSelfRef.soc_top__DOT__cpu__DOT__dbg_ascii_state),128);
    bufp->fullBit(oldp+212,(vlSelfRef.soc_top__DOT__cpu__DOT__set_mem_do_rinst));
    bufp->fullBit(oldp+213,(vlSelfRef.soc_top__DOT__cpu__DOT__set_mem_do_rdata));
    bufp->fullBit(oldp+214,(vlSelfRef.soc_top__DOT__cpu__DOT__set_mem_do_wdata));
    bufp->fullBit(oldp+215,(vlSelfRef.soc_top__DOT__cpu__DOT__latched_store));
    bufp->fullBit(oldp+216,(vlSelfRef.soc_top__DOT__cpu__DOT__latched_stalu));
    bufp->fullBit(oldp+217,(vlSelfRef.soc_top__DOT__cpu__DOT__latched_branch));
    bufp->fullBit(oldp+218,(vlSelfRef.soc_top__DOT__cpu__DOT__latched_compr));
    bufp->fullBit(oldp+219,(vlSelfRef.soc_top__DOT__cpu__DOT__latched_trace));
    bufp->fullBit(oldp+220,(vlSelfRef.soc_top__DOT__cpu__DOT__latched_is_lu));
    bufp->fullBit(oldp+221,(vlSelfRef.soc_top__DOT__cpu__DOT__latched_is_lh));
    bufp->fullBit(oldp+222,(vlSelfRef.soc_top__DOT__cpu__DOT__latched_is_lb));
    bufp->fullCData(oldp+223,(vlSelfRef.soc_top__DOT__cpu__DOT__latched_rd),5);
    bufp->fullIData(oldp+224,(vlSelfRef.soc_top__DOT__cpu__DOT__current_pc),32);
    bufp->fullBit(oldp+225,(vlSelfRef.soc_top__DOT__cpu__DOT__pcpi_timeout));
    bufp->fullIData(oldp+226,(vlSelfRef.soc_top__DOT__cpu__DOT__next_irq_pending),32);
    bufp->fullBit(oldp+227,(vlSelfRef.soc_top__DOT__cpu__DOT__do_waitirq));
    bufp->fullIData(oldp+228,(vlSelfRef.soc_top__DOT__cpu__DOT__alu_out),32);
    bufp->fullIData(oldp+229,(vlSelfRef.soc_top__DOT__cpu__DOT__alu_out_q),32);
    bufp->fullBit(oldp+230,(vlSelfRef.soc_top__DOT__cpu__DOT__alu_out_0));
    bufp->fullBit(oldp+231,(vlSelfRef.soc_top__DOT__cpu__DOT__alu_out_0_q));
    bufp->fullBit(oldp+232,(vlSelfRef.soc_top__DOT__cpu__DOT__alu_wait));
    bufp->fullBit(oldp+233,(vlSelfRef.soc_top__DOT__cpu__DOT__alu_wait_2));
    bufp->fullIData(oldp+234,(((IData)(vlSelfRef.soc_top__DOT__cpu__DOT__instr_sub)
                                ? (vlSelfRef.soc_top__DOT__cpu__DOT__reg_op1 
                                   - vlSelfRef.soc_top__DOT__cpu__DOT__reg_op2)
                                : (vlSelfRef.soc_top__DOT__cpu__DOT__reg_op1 
                                   + vlSelfRef.soc_top__DOT__cpu__DOT__reg_op2))),32);
    bufp->fullIData(oldp+235,((vlSelfRef.soc_top__DOT__cpu__DOT__reg_op1 
                               << (0x0000001fU & vlSelfRef.soc_top__DOT__cpu__DOT__reg_op2))),32);
    bufp->fullIData(oldp+236,((IData)((0x00000001ffffffffULL 
                                       & VL_SHIFTRS_QQI(33,33,5, 
                                                        (((QData)((IData)(
                                                                          (((IData)(vlSelfRef.soc_top__DOT__cpu__DOT__instr_sra) 
                                                                            | (IData)(vlSelfRef.soc_top__DOT__cpu__DOT__instr_srai)) 
                                                                           & (vlSelfRef.soc_top__DOT__cpu__DOT__reg_op1 
                                                                              >> 0x0000001fU)))) 
                                                          << 0x00000020U) 
                                                         | (QData)((IData)(vlSelfRef.soc_top__DOT__cpu__DOT__reg_op1))), 
                                                        (0x0000001fU 
                                                         & vlSelfRef.soc_top__DOT__cpu__DOT__reg_op2))))),32);
    bufp->fullBit(oldp+237,(vlSelfRef.soc_top__DOT__cpu__DOT__alu_eq));
    bufp->fullBit(oldp+238,(vlSelfRef.soc_top__DOT__cpu__DOT__alu_ltu));
    bufp->fullBit(oldp+239,(vlSelfRef.soc_top__DOT__cpu__DOT__alu_lts));
    bufp->fullBit(oldp+240,(vlSelfRef.soc_top__DOT__cpu__DOT__clear_prefetched_high_word_q));
    bufp->fullBit(oldp+241,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs_write));
    bufp->fullIData(oldp+242,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs_wrdata),32);
    bufp->fullIData(oldp+243,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs_rs1),32);
    bufp->fullIData(oldp+244,(vlSelfRef.soc_top__DOT__cpu__DOT__cpuregs_rs2),32);
    bufp->fullBit(oldp+245,((0U == (0xffff0000U & vlSelfRef.soc_top__DOT__cpu_mem_addr))));
    bufp->fullBit(oldp+246,((0x10000000U == (0xfffff000U 
                                             & vlSelfRef.soc_top__DOT__cpu_mem_addr))));
    bufp->fullBit(oldp+247,((0x20000000U == (0xfffff000U 
                                             & vlSelfRef.soc_top__DOT__cpu_mem_addr))));
    bufp->fullSData(oldp+248,((0x00003fffU & (vlSelfRef.soc_top__DOT__cpu_mem_addr 
                                              >> 2U))),16);
    bufp->fullSData(oldp+249,((0x00000fffU & (vlSelfRef.soc_top__DOT__cpu_mem_addr 
                                              >> 2U))),12);
    bufp->fullCData(oldp+250,(vlSelfRef.soc_top__DOT__gpio_inst__DOT__ddrb),8);
    bufp->fullCData(oldp+251,(vlSelfRef.soc_top__DOT__gpio_inst__DOT__portb),8);
    bufp->fullBit(oldp+252,((0x20000023U == vlSelfRef.soc_top__DOT__gpio_inst__DOT__mem_addr)));
    bufp->fullBit(oldp+253,((0x20000024U == vlSelfRef.soc_top__DOT__gpio_inst__DOT__mem_addr)));
    bufp->fullBit(oldp+254,((0x20000025U == vlSelfRef.soc_top__DOT__gpio_inst__DOT__mem_addr)));
    bufp->fullBit(oldp+255,(vlSelfRef.soc_top__DOT__gpio_inst__DOT__gpio_sel));
    bufp->fullBit(oldp+256,(vlSelfRef.clk));
    bufp->fullBit(oldp+257,(vlSelfRef.rst_n));
    bufp->fullCData(oldp+258,(vlSelfRef.gpio_pin_in),8);
    bufp->fullCData(oldp+259,(vlSelfRef.gpio_pin_out),8);
    bufp->fullCData(oldp+260,(vlSelfRef.gpio_pin_dir),8);
    bufp->fullIData(oldp+261,(((0x20000023U == vlSelfRef.soc_top__DOT__gpio_inst__DOT__mem_addr)
                                ? (IData)(vlSelfRef.gpio_pin_in)
                                : ((IData)(vlSelfRef.__VdfgRegularize_hebeb780c_0_0)
                                    ? ((0x20000024U 
                                        == vlSelfRef.soc_top__DOT__gpio_inst__DOT__mem_addr)
                                        ? (IData)(vlSelfRef.soc_top__DOT__gpio_inst__DOT__ddrb)
                                        : ((0x20000025U 
                                            == vlSelfRef.soc_top__DOT__gpio_inst__DOT__mem_addr)
                                            ? (IData)(vlSelfRef.soc_top__DOT__gpio_inst__DOT__portb)
                                            : 0U)) : 0U))),32);
}
